name: Workflow for codecov
on: 
  push:
    branches:
      - main
  pull_request:
    # file paths to consider in the event
    paths:
      - 'towhee/**'
      - '!**.md'
      - 'tests/**'
      - '.github/workflows/codecov.yml'

jobs:
  run:
    runs-on: towhee/towhee-ut:latest
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Setup Python
      uses: actions/setup-python@v3.0.0
      with:
        python-version: 3.8
    - name: Generate coverage report
      run: |
        conda run -n towhee-ut pip install coverage pytest pytest-xdist
        conda run -n towhee-ut pip install -r test_requirements.txt
        conda run -n towhee-ut coverage erase
        conda run -n towhee-ut coverage run -m pytest
    - name: Generate xml report
      run: |
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      id: upload_cov
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
    - name: Retry upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      id: retry_upload_cov
      with:
        files: ./coverage.xml
        fail_ci_if_error: true

