name: Workflow for codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Setup Python
      uses: actions/setup-python@v3.0.0
      with:
        python-version: 3.8
    - name: Generate coverage report
      run: |
        source /test/miniconda3/etc/profile.d/conda.sh
        conda env remove -n towhee-ut
        conda create -n towhee-ut python=3.8
        conda activate towhee-ut
        conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
        conda run -n towhee-ut pip install torch==1.8.0+cu101 -f https://download.pytorch.org/whl/cu101/torch_stable.html
        conda run -n towhee-ut pip install coverage pytest pytest-xdist
        conda run -n towhee-ut pip install -r test_requirements.txt
        conda run -n towhee-ut coverage erase
        conda run -n towhee-ut coverage run -m pytest
    - name: Generate xml report
      run: |
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      id: upload_cov
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
    - name: Retry upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      id: retry_upload_cov
      with:
        files: ./coverage.xml
        fail_ci_if_error: true

