name: Weekly CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    - cron: "0 0 * * 5"
  pull_request:
    # file paths to consider in the event
    paths:
      - '.github/workflows/weekly_ci.yml'

jobs:
  test:
    name: Test
    runs-on: self-hosted
    container: 
      image: towhee/towhee-ut:latest
      options: --user root
      volumes:
        - /__w/towhee/towhee:/__w/towhee/towhee
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.8
    - name: Run Test
      env:
        TOWHEE_WORKER: True
      run: |
        source /test/miniconda3/etc/profile.d/conda.sh
        conda env remove -n towhee-weekly
        conda create -n towhee-weekly python=3.8
        conda activate towhee-weekly
        conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
        cd  tests/testcases
        python3 -m pip install -U pip
        python3 -m pip install --no-cache-dir -r requirements.text
        cd  tests/testcases/hub
        export TOWHEE_WORKER=True
        python3 -W ignore execute_hub_operators.py
